name: run Norminette

on:
  pull_request:
    branches: [ "main", "103-commented-ci" ]
  workflow_call:
    inputs:
      enable_pr_comment:
        description: 'Enable PR comment'
        required: false
        default: true
        type: 'boolean'

jobs:
  run_norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install norminette
        run: |
          python -m pip install --upgrade pip setuptools
          pip install norminette
      - name : Run norminette
        id: norm
        continue-on-error: true
        run: |
          echo "\`\`\`sh" > norminette.md
          norminette -d >> norminette.md || echo "status=$?" >> $GITHUB_OUTPUT
          echo "\`\`\`" >> norminette.md
      - name: Create PR comment
        if: ${{ steps.norm.outputs.status != 0 }}
        run: |
          gh pr comment ${{ github.event.number }} --body-file norminette.md
        env:
          GITHUB_TOKEN: ${{ secrets.NORM_COMMENT }}
        
